class VisitorsController < ApplicationController
  layout 'home'

  def index
  	@q = User.with_role(:agent).ransack(params[:q])
    # file = "/home/mohsin/Project_Docs/PLQ/iso3166.csv"
    # CSV.foreach(file) do |row|
    #   # binding.pry
    #   Country.create(name: row[1], code: row[0])
    # end
  end

  def service_content
  	service_name = params[:service_name]

    case service_name
      when "restaurant"
        title = "Restaurant Reservations / Suggestions"
        image = "/assets/restaurant-popup.jpg"
        content = "<p>Technology in the form of search engines and various consumer apps has enabled users to find great restaurants and browse through reviews for recommendations. With all this functionality available what else would you need you may ask?</p><p>Answer. A knowledgeable and helpful person. Going through so many options, suggestions, and reviews can be very time consuming and frustrating when making a decision. PLQ eliminates this apparent problem by providing a local expert or just a local with who’s very knowledgeable on great food at a touch of a button.</p><p>Our provider network has been built using clear guidelines for each agent or vendor to ensure PLQ users and members of all types can find some one who can assist with making the right choice. In addition to our manual peer to peer solutions we have an extensive global directory of restaurants, which has been hand curated by our network of partners and providers which users can access for free.</p><p>For PLQ members there are added perks such as priority reservations with our selected partners and discounts all of which are automatically applied for our members when making a booking making each experience frictionless.</p><p>Join our network and start enjoying all we have to offer.</p>"
      when "chauffeur"
        title = "Chauffeur Services"
        image = "/assets/driver-services-popup.jpg"
        content = "<p>Transportation has been truly disrupted and for the better. Technology has taken the lead by offering various consumer apps that has enabled users to have on demand transport localised to where they are at a touch of a button.</p><p>Our network has been built using open source solutions for seamless service integrations. With all this functionality available PLQ has integrated 3rd party transportation services such as UBER directly into our mobile application for users to continue enjoy the seamless benefits provided by these great solutions.</p><p>PLQ users and members can also contact one of our agents providing chauffer services who can assist with making advance bookings or bookings that have special requests. This assistance can be very helpful for airport bookings for large parties or for special occasions such as weddings where dedicated bespoke services are essential.</p><p>For PLQ members there are added perks such as priority reservations with our selected partners and discounts all of which are automatically applied for our members when making a booking making each experience frictionless.</p><p>Join our network and start enjoying all we have to offer.</p>"
      when "interior"
        title = "Interior Design & Home Planning"
        image = "/assets/interior-design-popup.jpg"
        content = "<p>Consumer sites such as Pinterest has enabled users to find great inspiration and browse through pages and pages of home interiors. With all this content available the key to interior design and home planning success is design curation, creative knowledge and turnkey assistance.</p><p>Going through so many options, suggestions, and choices can be very time consuming and frustrating especially when working on a budget. PLQ address this apparent “luxury” problem by locating and providing a domain professional or an agent who can source the right person for the job.</p><p>Our provider network has been built using clear guidelines for each agent or provider to ensure PLQ users and members of all types can find some one who can assist them with making the right choice. In addition to our manual peer to peer solutions we have an extensive global directory of providers, which has been hand curated by our network of partners and providers which users can access for free.</p><p>For PLQ members there are added perks with our selected partners and discounts all of which are automatically applied for our members when making a hiring someone making the process frictionless.</p><p>Join our network and start enjoying all we have to offer.</p>"
      when "nightlife"
        title = "Nightlife & Event Hosting"
        image = "/assets/nightlife-popup.jpg"
        content = "<p>Arranging a night out is still something that consumers have trouble coordinating without the associated stress of making reservations, contacting friends with locations and times, arranging payment for groups, transportation to the venue, the list goes on.</p><p>Nightlife is one of the PLQ specialist services areas that we focus on providing simple social information to high end premium assistance ranging from information from local agents and venues about what events are happening in the area to full bespoke itinerary based bookings where one of our lifestyle agents arrange the complete experience and coordinate all associated events from start to finish.</p><p>PLQ members have added perks such as priority reservations with our selected partners. For exclusive events such as concerts or sporting events being a PLQ member ensures you have access to the most exclusive events.</p><p>Nightlife assistance can be very helpful when traveling or on holiday where knowing the right place and people is essential. Also for special occasions such as birthdays involving large parties things go to plan is paramount.</p><p>Join (hyperlink) our network and start enjoying all we have to offer.</p>"
      when "travel"
        title = "Travel Coordination"
        image = "/assets/travel-services-popup.jpg"
        content = "<p>The web has provided users with some great solutions when planning holidays and making travel arrangements. Sites such as Kayak.com and Booking.com have revolutionised the travel industry for both providers and consumers. The key factors when coordinating travel arrangements are time spend doing it and the associated costs and savings.</p><p>PLQ has focused our agent network on providing travel experts both localised to the destination where user is travelling to and domestically to ensure our users are connected with suitable service providers who can understand each user or member request.</p><p>Our travel provider network consists of boutique hotels to global hotel chains as well as public and private aviation services. We make this network available to our agents to ensure they have all the tools and information required to service our community of users and dedicated members with the best possible service regardless of budget or financial means.</p><p>PLQ members can enjoy added perks with our selected partners and discounts all of which are automatically applied for our members when making a reservation making the process frictionless.</p><p>Travel coordination can be very stressful and time consuming, so our solutions enable users to focus on their trip or holiday where knowing the right places to look is essential. We specialise in travel coordination for large groups and corporate bookings, which can be access via our memberships for fixed fee.</p><p>Join our network and start enjoying all we have to offer.</p>"
      when "communication"
        title = "24/7 Direct Communication"
        image = "/assets/24-7-communication-popup.jpg"
        content = "<p>PLQ has sourced some of the best personal assistance and lifestyle agents from across the globe to provide affiliate services to our users and members across our network. At the core of our business are our communication systems for our users and members to connect to with our providers.</p><p>We have integrated the best cross platform messaging and voice communication stacks for our users to always be able to speak or communicate with one of our providers 24/7 365* with just an Internet connection.</p><p>We make all our provider directories open to our users and members like an open phone book or contact list. We securely keep the required information on our user network to ensure our lifestyle agents and mangers have all the information required to service our community of users and dedicated members with the best possible service regardless of user or member tariff.</p><p>Both domestically or location based our providers ensure our users are always connected at a touch of a button. PLQ members can enjoy added services with our dedicated lifestyle agents and managers, which are there to provide a dedicated personalised service for all related lifestyle requests.</p><p>Join our network and start enjoying all we have to offer.</p>"
      when "accomodation"
        title = "Accommodation Sourcing"
        image = "/assets/accomodation-popup.jpg"
        content = "<p>Established platforms such as airbnb.com have provided great accommodation solutions for all occasions and budgets. When planning holidays and making travel arrangements key factors such as coordinating travel arrangements with accommodation is essential for an enjoyable experience.</p><p>PLQ has curated some of the best places to stay across the globe and integrated our network of accommodation experts both localised to the destination where user is travelling to and domestically to ensure our users are connected with suitable service providers who can understand each user or member request.</p><p>Our accommodation-sourcing network consists of property owners and hotel chains which act as providers on our network that users and members can access directly using our communication tools or coordinate using one of our allocated lifestyle agents.</p><p>We make this network available to our agents to ensure they have all the tools and information required to service our community of users and dedicated members with the best possible service regardless of budget or financial means.</p><p>PLQ members can enjoy added perks with our selected partners and discounts all of which are automatically applied for our members when making a reservation making the process frictionless.</p><p>Accommodation sourcing can be difficult to coordinate especially in peak seasons. Our solutions enable users to focus on enjoying the trip or holiday, we specialise in accommodation and coordination for large groups and corporate bookings, which can be access via our memberships for fixed fee.</p><p>Join our network and start enjoying all we have to offer.</p>"
      when "fashion"
        title = "Fashion & Style Consolation"
        image = "/assets/style-popup.jpg"
        content = "<p>On-line retail shopping has grown significantly with the development of the web and new hardware devices such as tablets. However, a day out at the stores for some retail therapy cannot be beaten especially when traveling or on holiday.</p><p>PLQ has sourced some of the best personal shoppers and stylists to provide affiliate services to our users and members across our network. Both localised domestically and location based our providers ensure our users are connected with suitable service providers who can understand each user or member request based on their preferences.</p><p>We have curated a directory of style looks (see platformlifestyle.com) for our user network as well as provided information where users can buy the selected items. We make all our directories available to our agents to ensure they have all the information required to service our community of users and dedicated members with the best possible service regardless of budget or financial means.</p><p>PLQ members can enjoy added perks with our selected partners and discounts all of which are automatically applied for our members when making a reservation making the process frictionless.</p><p>We all know gift buying especially around holiday season can be very stressful and time consuming, so our solutions enable users to focus on making the right choices where knowing the right places to look is essential.</p><p>Join our network and start enjoying all we have to offer.</p>"
      when "global"
        title = "Global Lifestyle Management Network"
        image = "/assets/global-network-popup.jpg"
        content = "<p>At the core of the PLQ is our global lifestyle management network. PLQ has sourced and built a dedicated lifestyle network from across the globe to provide on demand affiliate services to our users and members across our network.</p><p>Built on dedicated communication systems for our users and members to connect to with our network of providers we have dedicated our time to connecting the dots and creating a social lifestyle network with real life interactions.</p><p>Transparency is key for all users especially with the personal information that we are trusted with. We securely keep the required information on our user network to ensure our lifestyle agents and mangers have all the information required to service our community of users and dedicated members with the best possible service regardless of user or member tariff.</p><p>Both domestically or location based our providers ensure our users are always connected at a touch of a button. PLQ members can enjoy added services with our dedicated lifestyle managers, which are there to provide a dedicated personalised service for all lifestyle related requests.</p><p>Users will always be able to access our network with just an Internet connection and with the additional functionality of direct communication lifestyle management just became easier.</p><p>Join our network and start enjoying all we have to offer.</p>"
    end
    render :json => { title: title, image: image, content: content }
  end
end
